from .login_page import LoginPage
from .dashboard_page import DashboardPage
from .map_page import MapsPage
from .permission_page import PermissionPage
from .role_page import RolePage
from .company_page import CompanyPage
from .alarm_values_page import AlarmValuesPage
from .alarm_conditions_page import AlarmConditionsPage
from .alarm_triggers_page import AlarmTriggersPage
from .user_page import UserPage
from .email_page import EmailPage
from .breadcrumbs import BreadCrumbs
from .vessel_page import VesselPage
from .subcategory_page import SubCategoryPage
from .device_image_page import DeviceImagePage